version: "3"

services:
  mysql-db:
    image: mysql:8.0
    container_name: absen_data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: absen
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
    - "33061:3306"
    volumes:
    - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - app-tier

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    networks:
      - app-tier
    command:
      tail -f /dev/null

networks:
  app-tier:
    driver: bridge